name: documenter_ci

on:
  push:
    branches:
      - main

jobs:
  teroshdl-doc:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: TerosTechnology/teroshdl-documenter-action@main
      with:
        args: -i ./ --recursive --out html
