name: build-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: VLOG
      run: vlog 	+acc -source  +define+SIM -O0	$Source/EXE_Stage.v
